wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("save", views.save, name="save"),
    path("newPage", views.newPage, name="newPage"),
    path("random", views.random, name="random"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("wiki/<str:title>",views.post, name="post")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
import re

from . import util
from markdown2 import Markdown

from random import choice

class SearchForm(forms.Form):
    q = forms.CharField(label="search")

class EditForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="Definition")
    status = forms.CharField(label="Status")

converter = Markdown()

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def post(request, title):
    marked = util.get_entry(title)

    if marked != None:
        text = converter.convert(marked)
        return render(request, "encyclopedia/page.html", {
            "title": title,
            "text": text
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "title": title
        })

def random(request):
    entries = util.list_entries()
    selected = choice(entries)
    marked = util.get_entry(selected)
    return render(request, "encyclopedia/page.html", {
        "title": selected,
        "text": converter.convert(marked)
    })

def search(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            pattern = form.cleaned_data["q"]
            text = util.get_entry(pattern)
            if text != None:
                return render(request, "encyclopedia/page.html", {
                    "title": pattern,
                    "text": converter.convert(text) 
                })
            else:
                matcher = re.compile(pattern)
                entries = util.list_entries()
                found = []
                for entry in entries:
                    if(matcher.search(entry)) :
                        found.append(entry)
                if len(found) > 0:
                    return render(request, "encyclopedia/result.html", {
                        "matches": found
                    })
                else:
                    return render(request, "encyclopedia/error.html", {
                        "title": pattern,
                        "error": ""
                    })
        else:
            return render(request, "encyclopedia/error.html", {
                "error": form.errors
            })
    else:
        return render(request, "encyclopedia/error.html", {
            "title": request.method       
        })

def edit(request,title):
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "text": util.get_entry(title),
        "status": "old"
    })

def newPage(request):
    return render(request, "encyclopedia/edit.html", {
        "title": "",
        "text": "",
        "status": "new"
    })

def save(request):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            status = form.cleaned_data["status"]
            if status=="old" or util.get_entry(title) == None:
                util.save_entry(title,content)
                return render(request, "encyclopedia/page.html", {
                    "title": title,
                    "text": converter.convert(content)
                })
            else:
                return render(request, "encyclopedia/blocked.html", {
                    "title": title
                })
        else:
            return render(request, "encyclopedia/error.html", {
                "error": form.errors
            })
    else:
        return render(request, "encyclopedia/error.html", {
            "title": request.method
        })
        

wiki/encyclopedia/templates/encyclopedia/blocked.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Blocked
{% endblock %}

{% block body %}
    <h1>Operation Blocked</h1>

    <p>The page <a href="/wiki/{{ title }}">{{title}}</a> already exists on this Wiki!</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if status == "new" %}
        New Page
    {% else %}
        {{title}}
    {% endif %}
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:save' %}" method="post">
        {% csrf_token %}
    {% if title %}        
        <h3>{{title}}</h3>
        <input type="hidden" name="title" value="{{title}}"/>
    {% else %}
        <label for="title">Title:</label>
        <input type=text id="title" name="title" size="15" placeholder="Page Title"/>
        <br/>
    {% endif %}
        <textarea id="content" name="content">{{text}}</textarea>
        <input type="hidden" name="status" value="{{status}}"/>
        <input type="submit" value="Save"/>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    {% if error %}
        <h1>Submission Error:</h1>
        <h2>{{error}}</h2>
    {% else %}
        <h1>Error 404</h1>
        <h2>Page not found</h2>

        <p>The page <strong>{{title}}</strong> was not found on this Wiki!</p>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">                    
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    {{ text|safe }}
    <a href="/edit/{{title}}">Edit</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Matches
{% endblock %}

{% block body %}
    <h1>Matching Pages</h1>

    <ul>
        {% for match in matches %}
            <li><a href="/wiki/{{ match }}">{{ match }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}